/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlembicVersion {
  version_num: string;
}

export interface BurstGroups {
  best_shot_override_photo_id: string | null;
  best_shot_photo_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  updated_at: Generated<Timestamp>;
}

export interface BurstGroupSpecies {
  burst_group_id: string;
  confidence: number | null;
  created_at: Generated<Timestamp>;
  id: string;
  model_id: string | null;
  raw_label: string | null;
  raw_response: Json | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  source: string;
  species_id: string | null;
  status: string;
}

export interface BurstGroupTags {
  burst_group_id: string;
  tag_id: string;
}

export interface IntegrationCredentials {
  id: string;
  refresh_token: string;
  updated_at: Generated<Timestamp>;
}

export interface Jobs {
  attempts: number;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  id: string;
  job_type: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  max_attempts: number;
  payload: Json;
  run_after: Generated<Timestamp>;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface Locations {
  center_lat: number;
  center_lng: number;
  id: string;
  name: string;
  radius_meters: number;
}

export interface Photos {
  aperture: number | null;
  burst_group_id: string;
  camera_make: string | null;
  camera_model: string | null;
  created_at: Generated<Timestamp>;
  exposure_score: number | null;
  focal_length_mm: number | null;
  google_photos_id: string | null;
  gps_lat: number | null;
  gps_lng: number | null;
  grouping_locked: boolean;
  height: number | null;
  id: string;
  import_source: string;
  import_status: string;
  iso: number | null;
  location_id: string | null;
  phash: string | null;
  r2_key_medium: string;
  r2_key_original: string;
  r2_key_thumb: string;
  sharpness_score: number | null;
  shutter_speed: string | null;
  taken_at: Timestamp;
  width: number | null;
}

export interface ShareLinks {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  filter_params: Json | null;
  id: string;
  target_id: string | null;
  token: string;
  type: string;
  view_count: number;
}

export interface Species {
  common_name: string;
  ebird_code: string | null;
  id: string;
  scientific_name: string | null;
  slug: string;
}

export interface Tags {
  id: string;
  name: string;
  slug: string;
}

export interface DB {
  alembic_version: AlembicVersion;
  burst_group_species: BurstGroupSpecies;
  burst_group_tags: BurstGroupTags;
  burst_groups: BurstGroups;
  integration_credentials: IntegrationCredentials;
  jobs: Jobs;
  locations: Locations;
  photos: Photos;
  share_links: ShareLinks;
  species: Species;
  tags: Tags;
}
