"""add photos.grouping_locked for manual burst merge

Revision ID: 0d0490b33943
Revises: 5e4ca42e0b37
Create Date: 2026-09-12 13:27:21.242415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0490b33943'
down_revision: Union[str, Sequence[str], None] = '5e4ca42e0b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to false; the model itself
    # has no server_default so future inserts rely on the ORM's
    # default=False instead (kept out of the schema to match this
    # project's other boolean-shaped defaults).
    op.add_column(
        'photos',
        sa.Column('grouping_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.alter_column('photos', 'grouping_locked', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'grouping_locked')
    # ### end Alembic commands ###
