"""Initial schema

Revision ID: 5e4ca42e0b37
Revises: 
Create Date: 2026-09-11 17:26:28.486647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4ca42e0b37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burst_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('best_shot_photo_id', sa.UUID(), nullable=True),
    sa.Column('best_shot_override_photo_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['best_shot_override_photo_id'], ['photos.id'], name='fk_burst_groups_best_shot_override', use_alter=True),
    sa.ForeignKeyConstraint(['best_shot_photo_id'], ['photos.id'], name='fk_burst_groups_best_shot', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('run_after', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_type', 'dedupe_key', name='uq_jobs_type_dedupe')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('filter_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    op.create_table('species',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('ebird_code', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('burst_group_species',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('burst_group_id', sa.UUID(), nullable=False),
    sa.Column('species_id', sa.UUID(), nullable=True),
    sa.Column('raw_label', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['burst_group_id'], ['burst_groups.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_burst_group_species_burst_group_id'), 'burst_group_species', ['burst_group_id'], unique=False)
    op.create_table('burst_group_tags',
    sa.Column('burst_group_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['burst_group_id'], ['burst_groups.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('burst_group_id', 'tag_id')
    )
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('burst_group_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('google_photos_id', sa.String(), nullable=True),
    sa.Column('import_source', sa.String(), nullable=False),
    sa.Column('r2_key_original', sa.String(), nullable=False),
    sa.Column('r2_key_thumb', sa.String(), nullable=False),
    sa.Column('r2_key_medium', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('camera_make', sa.String(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('focal_length_mm', sa.Float(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('shutter_speed', sa.String(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('phash', sa.String(), nullable=True),
    sa.Column('sharpness_score', sa.Float(), nullable=True),
    sa.Column('exposure_score', sa.Float(), nullable=True),
    sa.Column('import_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['burst_group_id'], ['burst_groups.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_burst_group_id'), 'photos', ['burst_group_id'], unique=False)
    op.create_index(op.f('ix_photos_google_photos_id'), 'photos', ['google_photos_id'], unique=True)
    op.create_index(op.f('ix_photos_taken_at'), 'photos', ['taken_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_taken_at'), table_name='photos')
    op.drop_index(op.f('ix_photos_google_photos_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_burst_group_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('burst_group_tags')
    op.drop_index(op.f('ix_burst_group_species_burst_group_id'), table_name='burst_group_species')
    op.drop_table('burst_group_species')
    op.drop_table('tags')
    op.drop_table('species')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_table('locations')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('integration_credentials')
    op.drop_table('burst_groups')
    # ### end Alembic commands ###
