"""add photos.content_hash for duplicate detection

Revision ID: aad2933e1587
Revises: 0d0490b33943
Create Date: 2026-09-15 14:11:41.793580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad2933e1587'
down_revision: Union[str, Sequence[str], None] = '0d0490b33943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable, not backfilled here: existing rows stay NULL until
    # scripts/backfill_content_hashes.py runs. Postgres treats NULLs as
    # distinct from each other under a unique index, so that's safe —
    # only two rows that both have a real, matching hash would violate
    # the constraint (see app/jobs/import_photo.py).
    op.add_column('photos', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_photos_content_hash'), 'photos', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_content_hash'), table_name='photos')
    op.drop_column('photos', 'content_hash')
    # ### end Alembic commands ###
